global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'your-spring-app'
    static_configs:
      - targets: ['192.168.1.181:8083']  # Adresse IP de votre conteneur Spring Boot sur le port 8083

  - job_name: 'jenkins'
    static_configs:
      - targets: ['192.168.1.181:8080']  # Adresse IP de Jenkins sur le port 8080
