global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']  # Adresse locale de votre machine

  - job_name: 'spring-actuator-docker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.181:8083']  # Adresse IP de votre conteneur Docker
