global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'your-spring-app'
    metrics_path: '/actuator/prometheus'  # Chemin d'accès aux métriques de Spring Boot
    static_configs:
      - targets: ['192.168.1.181:8083']  # Adresse IP de votre application Spring Boot
